import pyautogui
import time

print(pyautogui.size())
while True:
    pyautogui.moveTo(100, 100)
    # pyautogui.rightClick()
    # pyautogui.moveTo(3750, 500, 0.5)
    # time.sleep(0.5)
    # pyautogui.moveTo(4000, 970, 0.5)
    # pyautogui.click()
    # time.sleep(0.3)
    # pyautogui.hotkey('ctrl', 'r')
    # pyautogui.moveTo(1500, 500)
    # pyautogui.click()
    # pyautogui.typewrite("nano stream.har")
    # pyautogui.typewrite(['enter'])
    # time.sleep(0.5)
    # pyautogui.hotkey('ctrl', 'shift', 'v')
    # time.sleep(1)
    # pyautogui.hotkey('ctrl', 'o')
    # pyautogui.typewrite(['enter'])
    # time.sleep(0.2)
    # pyautogui.hotkey('ctrl', 'x')
    # pyautogui.typewrite('./convert.sh')
    # pyautogui.typewrite(['enter'])
    # pyautogui.moveTo(2500, 350)
    # pyautogui.click()
    time.sleep(600)
